version: '3.7'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-webapp
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py

  grafana:
    build:
      context: .
      dockerfile: Dockerfile-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile-prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - webapp
