global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'webapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webapp:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.202:9100']
